/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicLoginPage;

import classes.user.Admin;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import operations.MultipleWindowHandle;
import userFrame.adminFrame.TabContainer;

/**
 *
 * @author cits
 */
public class Splash extends javax.swing.JFrame{

    /**
     * Creates new form Splash
     */
    JFrame own = this;
    public Splash() {
        initComponents();
        
        new SwingWorker(){
            @Override
            protected Object doInBackground() throws Exception {
                own.setOpacity((float) 1.0);
                for(float i=0;i<1.0;i+=0.01){
                    setOpacity(i);
                    try {
                        Thread.sleep(60);
                    } catch (InterruptedException ex) {
                    }
                }
                return null;
            }
        }.execute();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setOpacity(0.0F);
        setResizable(false);

        jButton1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon8/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("X");
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MultipleWindowHandle.hideState(this, new Search(this));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MultipleWindowHandle.hideState(this, new LoginPage(this, null));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Admin usr = new Admin("Rafi Khan", "01736813681", "rafikhan@usa.com", "N/A", "rafikhan", "1234");
        usr.setId("12345678");
//        usr.addButton(TabContainer.DASHBOARD);
        usr.addButton(TabContainer.EMPLOYEE_LIST);
        usr.addButton(TabContainer.ADD_BUS);
        usr.addButton(TabContainer.BOOK_BUS);
        usr.addButton(TabContainer.BUS_SCHUDULE);
        usr.addButton(TabContainer.ADD_ROUTE);
        usr.addButton(TabContainer.EMPLOYEE_RECUIT);
        usr.addButton(TabContainer.ADD_VOUCHER);
        //usr.addButton(TabContainer.PAYROLL);
        usr.addButton(TabContainer.REPORT);
        usr.addButton(TabContainer.REVENUE);        
        
        ArrayList<Admin> al = new ArrayList<Admin>();
        al.add(usr);
        
        try {
            ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream(new File("ADMIN")));
            os.writeObject(al);
            os.flush();
            os.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }      
        
//        Passenger usr1 = new Passenger("Rafi Khan", "01736813681", "rafikhan@usa.com", "N/A", "rafikhan", "1234");
//        usr1.setId("12345678");
//        usr1.addButton(TabContainer.DASHBOARD);
//        usr1.addButton(TabContainer.EMPLOYEE_LIST);
//        usr1.addButton(TabContainer.ADD_BUS);
//        usr1.addButton(TabContainer.BOOK_BUS);
//        usr1.addButton(TabContainer.BUS_SCHUDULE);
//        usr1.addButton(TabContainer.ADD_ROUTE);
//        usr1.addButton(TabContainer.EMPLOYEE_RECUIT);
//        ArrayList<Passenger> a2 = new ArrayList<Passenger>();
//        a2.add(usr1);
//        
//        try {
//            ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream(new File("PASSENGER")));
//            os.writeObject(a2);
//            os.flush();
//            os.close();
//        } catch (Exception ex) {
//            System.out.println(ex);
//        } 
//        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
