/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commonJinternalFrames;

import classes.Bus;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import operations.SystemErrorHandle;

/**
 *
 * @author rafikhan
 */
public class AddBusEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form addBus
     */
    public AddBusEmployee() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCompany = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldReg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSeats = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFare = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFareExtended = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxAC = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxActive = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(60, 74, 77));

        jPanel2.setBackground(new java.awt.Color(60, 74, 77));
        jPanel2.setLayout(new java.awt.GridLayout(9, 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Company");
        jPanel2.add(jLabel5);
        jPanel2.add(jTextFieldCompany);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration No :");
        jPanel2.add(jLabel1);
        jPanel2.add(jTextFieldReg);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seats :");
        jPanel2.add(jLabel2);
        jPanel2.add(jTextFieldSeats);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fare :");
        jPanel2.add(jLabel4);
        jPanel2.add(jTextFieldFare);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fare Ext. Ratio");
        jPanel2.add(jLabel7);
        jPanel2.add(jTextFieldFareExtended);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AC/non-AC :");
        jPanel2.add(jLabel3);

        jCheckBoxAC.setOpaque(false);
        jPanel2.add(jCheckBoxAC);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Active");
        jPanel2.add(jLabel6);

        jCheckBoxActive.setOpaque(false);
        jPanel2.add(jCheckBoxActive);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jTable1.setBackground(new java.awt.Color(60, 74, 77));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Reg", "Seats", "Ac", "Active", "UUID", "Fare", "Extended Ratio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jSeparator1)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Table");

        jMenuItem1.setText("Load Data into Table");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save Data from Table");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Clear Table");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() < 0){
            jTextFieldCompany.setText("");
            jTextFieldReg.setText("");
            jTextFieldSeats.setText("");
            jCheckBoxAC.setSelected(false);
            jCheckBoxActive.setSelected(false);
        }
        else{
            int rowKey = jTable1.getSelectedRow();
            jTextFieldCompany.setText((dm.getValueAt(rowKey, 0)).toString());
            jTextFieldReg.setText((dm.getValueAt(rowKey, 1)).toString());
            jTextFieldSeats.setText((dm.getValueAt(rowKey, 2)).toString());
            
            if(Boolean.valueOf(dm.getValueAt(rowKey, 3).toString())==null){
                jCheckBoxAC.setSelected(false);
            }else if(Boolean.valueOf(dm.getValueAt(rowKey, 3).toString())==true){
                jCheckBoxAC.setSelected(true);
            }else{
                jCheckBoxAC.setSelected(false);
            }
            if(Boolean.valueOf(dm.getValueAt(rowKey, 4).toString())==null){
                jCheckBoxActive.setSelected(false);
            }else if(Boolean.valueOf(dm.getValueAt(rowKey, 4).toString())==true){
                jCheckBoxActive.setSelected(true);
            }else{
                jCheckBoxActive.setSelected(false);
            }
            jTextFieldFare.setText(dm.getValueAt(rowKey, 6).toString());
            jTextFieldFareExtended.setText(dm.getValueAt(rowKey, 7).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()>-1){
            jTable1.setValueAt(jTextFieldCompany.getText(), jTable1.getSelectedRow(), 0);
            jTable1.setValueAt(jTextFieldReg.getText(), jTable1.getSelectedRow(), 1);
            jTable1.setValueAt(jTextFieldSeats.getText(), jTable1.getSelectedRow(), 2);
            jTable1.setValueAt(jCheckBoxAC.isSelected(), jTable1.getSelectedRow(), 3);
            jTable1.setValueAt(jCheckBoxActive.isSelected(), jTable1.getSelectedRow(), 4);
            jTable1.setValueAt(jTextFieldFare.getText(), jTable1.getSelectedRow(), 6);
            jTable1.setValueAt(jTextFieldFareExtended.getText(), jTable1.getSelectedRow(), 7);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTable1.clearSelection();
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.addRow(new Object[]{jTextFieldCompany.getText(),jTextFieldReg.getText(),jTextFieldSeats.getText(),jCheckBoxAC.isSelected(),jCheckBoxActive.isSelected(), "", jTextFieldFare.getText(), jTextFieldFareExtended.getText()});
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        jTable1MouseClicked(null);
    }//GEN-LAST:event_jTable1PropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            if(jTable1.getSelectedRow()>-1){
                DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
                dm.removeRow(jTable1.getSelectedRow());
                jTable1.setModel(dm);
                jTextFieldCompany.setText("");
                jTextFieldReg.setText("");
                jTextFieldSeats.setText("");
                jCheckBoxAC.setSelected(false);
                jCheckBoxActive.setSelected(false);
                jTextFieldFare.setText("");
                jTextFieldFareExtended.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showOptionDialog(null, "Current Data will be replaced", "Overwrite Data", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, null) == JOptionPane.OK_OPTION){
            new SwingWorker(){

                    float progress=0;
                    JProgressBar bar = new JProgressBar();
                    JOptionPane pane = new JOptionPane(bar);
                    JDialog dialLog = pane.createDialog(null, "Loading");

                    @Override
                    protected void done() {
                        dialLog.setTitle("Done");
                        jTable1.clearSelection();
                        jTable1.setVisible(true);
                        new SwingWorker() {
                            @Override
                            protected Object doInBackground() throws Exception {
                                Thread.sleep(5000);
                                dialLog.dispose();
                                return null;
                            }
                        }.execute();
                    }

                    @Override
                    protected void process(List list) {

                        progress = Float.parseFloat(list.get(list.size()-1).toString());

                        bar.setValue((int) progress);
                    }

                    @Override
                    protected Object doInBackground(){

                        jTable1.setVisible(false);

                    /////////////////////////////Editable:START//////////////////////////////
                    ArrayList<Bus> list = new ArrayList<Bus>();
                    for(int i=0;i<jTable1.getRowCount();i++){
                        list.add(new Bus(jTable1.getValueAt(i, 0).toString(), jTable1.getValueAt(i, 1).toString(), Integer.parseInt(jTable1.getValueAt(i, 2).toString()), Boolean.parseBoolean(jTable1.getValueAt(i, 3).toString()), Boolean.parseBoolean(jTable1.getValueAt(i, 4).toString()), jTable1.getValueAt(i, 5).toString(), Integer.valueOf(jTable1.getValueAt(i, 6).toString()), Float.valueOf(jTable1.getValueAt(i, 7).toString()) ));

                        publish( ((float) 100/jTable1.getRowCount()) + progress);////////progressBar///////////////

                        try{
                            Thread.sleep(5);
                        }catch(Exception ex){
                        }
                    }
                    publish(100);
                    /////////////////////////////Editable:END//////////////////////////////

                        new SwingWorker(){
                            @Override
                            protected Object doInBackground() throws Exception {
                                dialLog.setModal(false);
                                dialLog.setLocation(GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth() - dialLog.getSize().width,
                                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight() 
                                                - dialLog.getSize().height 
                                                - (Toolkit.getDefaultToolkit().getScreenSize().height 
                                                        - GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height) );
                                dialLog.setVisible(true);
                                return null;
                            }
                        }.execute();

                        /////////////////////////////Editable:START//////////////////////////////
                        try{
                            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(new File("BUS")));
                            oos.writeObject(list);
                            oos.flush();
                            oos.close();
                        }catch(Exception ex){
                            if(JOptionPane.showOptionDialog(null, "Send Error report", "File write Exception", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null)==JOptionPane.OK_OPTION){
                                    SystemErrorHandle.reportError(ex);
                                }
                        }
                        /////////////////////////////Editable:END//////////////////////////////
                        return true;
                    }

                }.execute();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new SwingWorker(){
            
                float progress=0;
                JProgressBar bar = new JProgressBar();
                JOptionPane pane = new JOptionPane(bar);
                JDialog dialLog = pane.createDialog(null, "Loading");
                        
                @Override
                protected void done() {
                    dialLog.setTitle("Done");
                    jTable1.clearSelection();
                    jTable1.setVisible(true);
                    new SwingWorker() {
                        @Override
                        protected Object doInBackground() throws Exception {
                            Thread.sleep(5000);
                            dialLog.dispose();
                            return null;
                        }
                    }.execute();
                }

                @Override
                protected void process(List list) {
                    
                    progress = Float.parseFloat(list.get(list.size()-1).toString());
                    
                    bar.setValue((int) progress);
                }

                @Override
                protected Object doInBackground(){
                    
                    jTable1.setVisible(false);
                    
                /////////////////////////////Editable:START//////////////////////////////
                    ArrayList<Bus> list;
                try{
                    ObjectInputStream ois = new ObjectInputStream(new FileInputStream(new File("BUS")));
                    list = (ArrayList<Bus>) ois.readObject();
                    ois.close();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Data Retrive Failed");
                    return false;
                }
                /////////////////////////////Editable:END//////////////////////////////
                    
                    new SwingWorker(){
                        @Override
                        protected Object doInBackground() throws Exception {
                            dialLog.setModal(false);
                            dialLog.setLocation(GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth() - dialLog.getSize().width,
                                    GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight() 
                                            - dialLog.getSize().height 
                                            - (Toolkit.getDefaultToolkit().getScreenSize().height 
                                                    - GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height) );
                            dialLog.setVisible(true);
                            return null;
                        }
                    }.execute();
                    
                    /////////////////////////////Editable:START//////////////////////////////
                    DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
                    dm.setRowCount(0);
                    for(int i=0;i<list.size();i++){
                        dm.addRow(new Object[]{list.get(i).getCompany(),list.get(i).getRegNo(), list.get(i).getSeats(), list.get(i).isAc(), list.get(i).isInService(), list.get(i).getId(), list.get(i).getSeatFare(), list.get(i).getFareExtendedRatio()});
                        
                        publish( ((float) 100/list.size()) + progress);////////progressBar///////////////
                        
                        try{
                            Thread.sleep(5);
                        }catch(Exception ex){
                            if(JOptionPane.showOptionDialog(null, "Create Error Report", "Thread Inturupt Exception", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null)==JOptionPane.OK_OPTION){
                                SystemErrorHandle.reportError(ex);
                            }
                        }
                    }
                    /////////////////////////////Editable:END//////////////////////////////
                    publish(100);
                    jTable1.setModel(dm);
                    return true;
                }
                
            }.execute();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.setRowCount(0);
        jTable1.setModel(dm);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBoxAC;
    private javax.swing.JCheckBox jCheckBoxActive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCompany;
    private javax.swing.JTextField jTextFieldFare;
    private javax.swing.JTextField jTextFieldFareExtended;
    private javax.swing.JTextField jTextFieldReg;
    private javax.swing.JTextField jTextFieldSeats;
    // End of variables declaration//GEN-END:variables
}
