/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commonJinternalFrames;

import classes.BusSchedule;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import operations.FindBusByID;
import operations.ReadCityFile;
import operations.SystemErrorHandle;
import userFrame.adminFrame.EmployeeEditPanel;

/**
 *
 * @author rafikhan
 */
public class AddBusSchudule extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusSchudule
     */
    public AddBusSchudule() {
        initComponents();
        jComboBox1.setModel(new DefaultComboBoxModel<>(ReadCityFile.read()));
        jComboBox2.setModel(new DefaultComboBoxModel<>(ReadCityFile.read()));
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(60, 74, 77));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus", "Start Date", "End Date", "Depart City", "Arrive City", "Arrive Time", "Depart Time", "Seat Available", "Fare", "UUID", "Active"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setBackground(new java.awt.Color(60, 74, 77));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(60, 74, 77));
        jPanel2.setLayout(new java.awt.GridLayout(12, 3));

        jLabel2.setText("Start Date :");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2);
        jPanel2.add(datePicker1);

        jLabel1.setText("End Date :");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel1);
        jPanel2.add(datePicker2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Depart City :");
        jPanel2.add(jLabel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arrive City :");
        jPanel2.add(jLabel5);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox2);

        jLabel3.setText("Depart Time :");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel3);
        jPanel2.add(jTextField1);

        jLabel6.setText("Arrive Time :");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel6);
        jPanel2.add(jTextField3);

        jLabel10.setText("Seat Avail.");
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel10);

        jTextField5.setEditable(false);
        jPanel2.add(jTextField5);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fare :");
        jPanel2.add(jLabel12);

        jTextField6.setEditable(false);
        jPanel2.add(jTextField6);

        jLabel9.setText("Bus :");
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jLabel11.setText("Active :");
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel11);
        jPanel2.add(jCheckBox1);

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Table");

        jMenuItem2.setText("Load Data to Table");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save Date From Table");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Clear Table");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            dm.addRow(new Object[]{
            jButton1.getText(),
            datePicker1.getText(),
            datePicker2.getText(),
            jComboBox1.getSelectedItem().toString(),
            jComboBox2.getSelectedItem().toString(),
            jTextField1.getText(),
            jTextField3.getText(),
            FindBusByID.getSeatByReg(jButton1.getText()),
            FindBusByID.getTotalFareByReg(jButton1.getText()),
            "",
            jCheckBox1.isSelected()
        });
            jTable1.setModel(dm);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.setRowCount(0);
        jTable1.setModel(dm);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
new SwingWorker(){
            
                float progress=0;
                JProgressBar bar = new JProgressBar();
                JOptionPane pane = new JOptionPane(bar);
                JDialog dialLog = pane.createDialog(null, "Loading");
                        
                @Override
                protected void done() {
                    dialLog.setTitle("Done");
                    jTable1.clearSelection();
                    jTable1.setVisible(true);
                    new SwingWorker() {
                        @Override
                        protected Object doInBackground() throws Exception {
                            Thread.sleep(5000);
                            dialLog.dispose();
                            return null;
                        }
                    }.execute();
                }

                @Override
                protected void process(List list) {
                    
                    progress = Float.parseFloat(list.get(list.size()-1).toString());
                    
                    bar.setValue((int) progress);
                }

                @Override
                protected Object doInBackground(){
                    
                    jTable1.setVisible(false);
                    
                /////////////////////////////Editable:START//////////////////////////////
                    ArrayList<BusSchedule> list;
                try{
                    ObjectInputStream ois = new ObjectInputStream(new FileInputStream(new File("SCHEDULE")));
                    list = (ArrayList<BusSchedule>) ois.readObject();
                    ois.close();
                }catch(Exception ex){
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(null, "Data Retrive Failed");
                    return false;
                }
                /////////////////////////////Editable:END//////////////////////////////
                    
                    new SwingWorker(){
                        @Override
                        protected Object doInBackground() throws Exception {
                            dialLog.setModal(false);
                            dialLog.setLocation(GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth() - dialLog.getSize().width,
                                    GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight() 
                                            - dialLog.getSize().height 
                                            - (Toolkit.getDefaultToolkit().getScreenSize().height 
                                                    - GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height) );
                            dialLog.setVisible(true);
                            return null;
                        }
                    }.execute();
                    
                    /////////////////////////////Editable:START//////////////////////////////
                    DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
                    dm.setRowCount(0);
                    for(int i=0;i<list.size();i++){
                        dm.addRow(new Object[]{
                            list.get(i).getBusReg(),
                            list.get(i).getStart(),
                            list.get(i).getEnd(), 
                            list.get(i).getDepartCity(), 
                            list.get(i).getArriveCity(), 
                            list.get(i).getArriving(), 
                            list.get(i).getDepart(), 
                            list.get(i).getSeatAvailable(), 
                            FindBusByID.getTotalFareByReg(list.get(i).getBusReg()), 
                            list.get(i).getId(),
                            list.get(i).isActive()
                            });   
							
                        publish( ((float) 100/list.size()) + progress);////////progressBar///////////////
                        
                        try{
                            Thread.sleep(5);
                        }catch(Exception ex){
                            if(JOptionPane.showOptionDialog(null, "Create Error Report", "Thread Inturupt Exception", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null)==JOptionPane.OK_OPTION){
                                SystemErrorHandle.reportError(ex);
                            }
                        }
                    }
                    /////////////////////////////Editable:END//////////////////////////////
                    publish(100);
                    jTable1.setModel(dm);
                    return true;
                }
                
            }.execute();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showOptionDialog(null, "Current Data will be replaced", "Overwrite Data", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null, null, null) == JOptionPane.OK_OPTION){
            new SwingWorker(){

                    float progress=0;
                    JProgressBar bar = new JProgressBar();
                    JOptionPane pane = new JOptionPane(bar);
                    JDialog dialLog = pane.createDialog(null, "Loading");

                    @Override
                    protected void done() {
                        dialLog.setTitle("Done");
                        jTable1.clearSelection();
                        jTable1.setVisible(true);
                        new SwingWorker() {
                            @Override
                            protected Object doInBackground() throws Exception {
                                Thread.sleep(5000);
                                dialLog.dispose();
                                return null;
                            }
                        }.execute();
                    }

                    @Override
                    protected void process(List list) {

                        progress = Float.parseFloat(list.get(list.size()-1).toString());

                        bar.setValue((int) progress);
                    }

                    @Override
                    protected Object doInBackground(){

                        jTable1.setVisible(false);

                    /////////////////////////////Editable:START//////////////////////////////
                    ArrayList<BusSchedule> list = new ArrayList<BusSchedule>();
                    for(int i=0;i<jTable1.getRowCount();i++){
                        list.add(new BusSchedule(
                                                jTable1.getValueAt(i, 0).toString(),
                                                jTable1.getValueAt(i, 1).toString(),
                                                jTable1.getValueAt(i, 2).toString(),
                                                jTable1.getValueAt(i, 3).toString(),
                                                jTable1.getValueAt(i, 4).toString(),
                                                jTable1.getValueAt(i, 5).toString(),
                                                jTable1.getValueAt(i, 6).toString(),
                                                Integer.parseInt(jTable1.getValueAt(i, 7).toString()),
                                                jTable1.getValueAt(i, 9).toString(),
                                                Boolean.valueOf(jTable1.getValueAt(i, 10).toString()
                                        )));
                        
                        publish( ((float) 100/jTable1.getRowCount()) + progress);////////progressBar///////////////

                        try{
                            Thread.sleep(5);
                        }catch(Exception ex){
                        }
                    }
                    publish(100);
                    /////////////////////////////Editable:END//////////////////////////////

                        new SwingWorker(){
                            @Override
                            protected Object doInBackground() throws Exception {
                                dialLog.setModal(false);
                                dialLog.setLocation(GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth() - dialLog.getSize().width,
                                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight() 
                                                - dialLog.getSize().height 
                                                - (Toolkit.getDefaultToolkit().getScreenSize().height 
                                                        - GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().height) );
                                dialLog.setVisible(true);
                                return null;
                            }
                        }.execute();

                        /////////////////////////////Editable:START//////////////////////////////
                        try{
                                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(new File("SCHEDULE")));
                                oos.writeObject(list);
                                oos.flush();
                                oos.close();
                        }catch(Exception ex){
                                if(JOptionPane.showOptionDialog(null, "Send Error report", "File write Exception", JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null)==JOptionPane.OK_OPTION){
                                                SystemErrorHandle.reportError(ex);
                                        }
                        }
                        /////////////////////////////Editable:END//////////////////////////////
                        return true;
                    }

                }.execute();
            }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        datePicker1.setText(jTable1.getValueAt(row, 1).toString());
        datePicker2.setText(jTable1.getValueAt(row, 2).toString());
        jComboBox1.setSelectedItem(jTable1.getValueAt(row, 3));
        jComboBox2.setSelectedItem(jTable1.getValueAt(row, 4));
        jTextField1.setText(jTable1.getValueAt(row, 5).toString());
        jTextField3.setText(jTable1.getValueAt(row, 6).toString());
        jTextField5.setText(jTable1.getValueAt(row, 7).toString());
        jTextField6.setText(jTable1.getValueAt(row, 8).toString());
        jButton1.setText(jTable1.getValueAt(row, 0).toString());
        jCheckBox1.setSelected(Boolean.valueOf(jTable1.getValueAt(row, 10).toString()));
        
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()>-1){
            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            dm.removeRow(jTable1.getSelectedRow());
            jTable1.setModel(dm);
            datePicker1.setText("");
            datePicker2.setText("");
            jComboBox1.setSelectedIndex(-1);
            jComboBox2.setSelectedIndex(-1);
            jTextField1.setText("");
            jTextField3.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jButton1.setText("");
            jCheckBox1.setSelected(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()>-1){
            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();
            jTable1.setValueAt(jButton1.getText() , row, 0);
            jTable1.setValueAt(datePicker1.getText() , row, 1);
            jTable1.setValueAt(datePicker2.getText() , row, 2);
            jTable1.setValueAt(jComboBox1.getSelectedItem().toString() , row, 3);
            jTable1.setValueAt(jComboBox2.getSelectedItem().toString() , row, 4);
            jTable1.setValueAt(jTextField1.getText() , row, 5);
            jTable1.setValueAt(jTextField3.getText() , row, 6);
            jTable1.setValueAt(FindBusByID.getSeatByReg(jButton1.getText()) , row, 7);
            jTable1.setValueAt(FindBusByID.getTotalFareByReg(jButton1.getText()) , row, 8);
            jTable1.setValueAt(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString() , row, 9);
            jTable1.setValueAt(jCheckBox1.isSelected() , row, 10);

            jTable1.setModel(dm);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        JDialog dialog =null;
//        dialog = new JOptionPane(new SelectBus(dialog, jButton1).getContentPane(), -1, JOptionPane.DEFAULT_OPTION, null, new Object[]{}, null).createDialog("Select Bus");
//        dialog.pack();
//        dialog.setVisible(true);
        new SelectBus(jButton1).setVisible(true);
        //.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
