/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package commonJinternalFrames;

import classes.Payment;
import classes.Ticket;
import classes.Voucher;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import operations.FindTicket;
import operations.ReadSchudule;
import operations.ReadVoucher;

/**
 *
 * @author rafikhan
 */
public class MakePayment extends javax.swing.JPanel {

    /**
     * Creates new form MakePayment
     */
    JTable table;
    public MakePayment(JTable table) {
        initComponents();
        this.table = table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Voucher Code :");
        jPanel1.add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String text = jTextField1.getText();
        if(!jTextField1.getText().equals("")){
            Voucher vo = ReadVoucher.FindVoucher(text);
            int row = table.getSelectedRow();
            if(vo!=null){
                if( !Boolean.valueOf(table.getValueAt(row, 6).toString()) ){
    //                table.setValueAt( true, row, 6);
    //                table.setValueAt(vo.getCouponCode(), row, 7);
                    if( ((Integer)table.getValueAt(row, 5)) == vo.getAmount()){
                        ReadVoucher.FindAndDeleteVoucher(vo.getCouponCode());
                        ReadSchudule.incrementSchudule(table.getValueAt(row, 0).toString());
                        Ticket t = new Ticket(
                                table.getValueAt(row, 0).toString(),
                                table.getValueAt(row, 3).toString(),
                                table.getValueAt(row, 1).toString(),
                                table.getValueAt(row, 2).toString(),
                                Integer.valueOf(table.getValueAt(row, 4).toString()),
                                Integer.valueOf( table.getValueAt(row, 5).toString() )
                        );
                        t.setPayment( new Payment(true, table.getValueAt(row, 5).toString()) );
                        FindTicket.updateTicket(t);
                    }else{
                        JOptionPane.showMessageDialog(this, "Amount does not match");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Payment Already Done");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Not Found");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Please Enter Coupon Code");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
